const bankData = [
    {
        id: 'nubank_padrao',
        name: 'Nubank (Padrão)',
        toolName: 'Caixinhas (RDB)',
        asset: 'RDB',
        rentability: 100,
        maxDepositText: 'R$ 250 mil (FGC)',
        maxDepositValue: 0,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Liquidez imediata apenas na caixinha "Reserva de Emergência".',
        recommendations: { emergency: true, short_term: true, maximize: false },
        type: 'standard'
    },
    {
        id: 'nubank_meta',
        name: 'Nubank (Meta)',
        toolName: 'Caixinha Turbo',
        asset: 'RDB',
        rentability: 115,
        maxDepositText: 'R$ 5.000',
        maxDepositValue: 5000,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Condição: Movimentar R$900/mês.',
        recommendations: { emergency: true, short_term: true, maximize: true },
        type: 'promo'
    },
    {
        id: 'nubank_plus',
        name: 'Nubank+ / UV',
        toolName: 'Caixinha Turbo',
        asset: 'RDB',
        rentability: 120,
        maxDepositText: 'R$ 10.000',
        maxDepositValue: 10000,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Condição: Ser assinante Nubank+ ou cliente Ultravioleta.',
        recommendations: { emergency: true, short_term: true, maximize: true },
        type: 'promo'
    },
    {
        id: 'inter_cdb',
        name: 'Inter (CDB)',
        toolName: 'Meu Porquinho',
        asset: 'CDB',
        rentability: 100,
        maxDepositText: 'R$ 250 mil (FGC)',
        maxDepositValue: 0,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'D+1 (dias úteis).',
        liquidityImmediate: false,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: '',
        recommendations: { emergency: false, short_term: true, maximize: false },
        type: 'standard'
    },
    {
        id: 'inter_lci',
        name: 'Inter (LCI)',
        toolName: 'Meu Porquinho',
        asset: 'LCI',
        rentability: 93,
        maxDepositText: 'R$ 250 mil (FGC)',
        maxDepositValue: 0,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: false,
        ir: 'Isento.',
        liquidity: 'Carência de 360 dias.',
        liquidityImmediate: false,
        minDeposit: 1,
        prazoMinimo: 360,
        prazoMaximo: 0,
        extra: 'Para metas de médio/longo prazo devido à isenção fiscal.',
        recommendations: { emergency: false, short_term: false, maximize: true },
        type: 'standard'
    },
    {
        id: 'picpay_padrao',
        name: 'PicPay (Padrão)',
        toolName: 'Cofrinhos',
        asset: 'CDB',
        rentability: 102,
        maxDepositText: 'R$ 250 mil (FGC)',
        maxDepositValue: 0,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: '',
        recommendations: { emergency: true, short_term: true, maximize: false },
        type: 'standard'
    },
    {
        id: 'picpay_plus',
        name: 'PicPay+',
        toolName: 'Cofrinho Turbinado',
        asset: 'CDB',
        rentability: 121,
        maxDepositText: 'R$ 10.000',
        maxDepositValue: 10000,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Condição: Ser assinante PicPay+ ou cumprir metas.',
        recommendations: { emergency: true, short_term: true, maximize: true },
        type: 'promo'
    },
    {
        id: 'mercadopago_padrao',
        name: 'Mercado Pago',
        toolName: 'Conta Remunerada',
        asset: 'Conta de Pagamento (Títulos Públicos)',
        rentability: 100,
        maxDepositText: 'Não informado',
        maxDepositValue: Number.POSITIVE_INFINITY,
        fgc: false,
        fgcDetails: 'Não possui cobertura do FGC.',
        iof: false,
        ir: 'diario',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 0,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Rendimento automático sobre o saldo.',
        recommendations: { emergency: true, short_term: true, maximize: false },
        type: 'standard'
    },
    {
        id: 'mercadopago_meta',
        name: 'Mercado Pago (Meta)',
        toolName: 'Cofrinho Turbinado',
        asset: 'Conta de Pagamento (Títulos Públicos)',
        rentability: 115,
        maxDepositText: 'R$ 5.000',
        maxDepositValue: 5000,
        fgc: false,
        fgcDetails: 'Não possui cobertura do FGC.',
        iof: false,
        ir: 'diario',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 0,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Condição: Movimentar R$1.000/mês.',
        recommendations: { emergency: false, short_term: true, maximize: true },
        type: 'promo'
    },
    {
        id: 'mercadopago_meliplus',
        name: 'Mercado Pago (Meli+)',
        toolName: 'Cofrinho Turbinado',
        asset: 'Conta de Pagamento (Títulos Públicos)',
        rentability: 120,
        maxDepositText: 'R$ 10.000',
        maxDepositValue: 10000,
        fgc: false,
        fgcDetails: 'Não possui cobertura do FGC.',
        iof: false,
        ir: 'diario',
        liquidity: 'Imediata (24/7).',
        liquidityImmediate: true,
        minDeposit: 0,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Condição: Ser assinante Meli+.',
        recommendations: { emergency: true, short_term: true, maximize: true },
        type: 'promo'
    },
    {
        id: 'pagbank_padrao',
        name: 'PagBank',
        toolName: 'Cofrinho',
        asset: 'CDB',
        rentability: 101,
        maxDepositText: 'R$ 250 mil (FGC)',
        maxDepositValue: 0,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Diária.',
        liquidityImmediate: false,
        minDeposit: 0,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: '',
        recommendations: { emergency: false, short_term: true, maximize: false },
        type: 'standard'
    },
    {
        id: 'pagbank_promo',
        name: 'PagBank (Promo)',
        toolName: 'CDB Promocional',
        asset: 'CDB',
        rentability: 130,
        maxDepositText: 'Varia por oferta',
        maxDepositValue: Number.POSITIVE_INFINITY,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Prazo fixo (ex: 2 meses).',
        liquidityImmediate: false,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 60,
        extra: 'Geralmente para novos clientes, com prazo de vencimento.',
        recommendations: { emergency: false, short_term: false, maximize: true },
        type: 'promo'
    },
    {
        id: 'neon_padrao',
        name: 'Neon (Progressivo)',
        toolName: 'CDB Neon',
        asset: 'CDB',
        rentability: 113,
        rentabilityDisplay: '100% a 113%',
        maxDepositText: 'R$ 250 mil (FGC)',
        maxDepositValue: 0,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Diária.',
        liquidityImmediate: false,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: 'Rendimento aumenta a cada 6 meses.',
        recommendations: { emergency: false, short_term: true, maximize: false },
        type: 'standard'
    },
    {
        id: 'neon_promo',
        name: 'Neon (Promo)',
        toolName: 'CDB Promocional',
        asset: 'CDB',
        rentability: 150,
        maxDepositText: 'Varia por oferta',
        maxDepositValue: Number.POSITIVE_INFINITY,
        fgc: true,
        fgcDetails: 'Sim, garantido pelo FGC.',
        iof: true,
        ir: 'Retido no resgate.',
        liquidity: 'Prazo fixo (ex: 2 meses).',
        liquidityImmediate: false,
        minDeposit: 1,
        prazoMinimo: 0,
        prazoMaximo: 60,
        extra: 'Geralmente para novos clientes, com prazo de vencimento.',
        recommendations: { emergency: false, short_term: false, maximize: true },
        type: 'promo'
    },
    {
        id: 'bb',
        name: 'Banco do Brasil',
        toolName: 'Cofrinho BB',
        asset: 'Fundo de Renda Fixa',
        rentability: 88,
        maxDepositText: 'Não informado',
        maxDepositValue: Number.POSITIVE_INFINITY,
        fgc: false,
        fgcDetails: 'Não, por ser um fundo de investimento.',
        iof: true,
        ir: 'Come-cotas semestral.',
        liquidity: 'Diária (dias úteis).',
        liquidityImmediate: false,
        minDeposit: 0.01,
        prazoMinimo: 0,
        prazoMaximo: 0,
        extra: '',
        recommendations: { emergency: false, short_term: false, maximize: false },
        type: 'standard'
    }
];